version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    
  api:
    build: .
    ports: 
      - 8001:8001
    environment:
      - PORT=8001
      - DATABASE_URL=db
    depends_on:
      - db
