version: '3.9'

name: nlquery

services:
  db:
    container_name: nlquery-db
    image: postgres:14  
    environment:
      POSTGRES_USER: nlquery
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
      container_name: nlquery-backend
      build:
        context: server
        dockerfile: Dockerfile.multistage
      ports:
        - "8001:8001"  # Adjust the port as needed
      depends_on:
        - db
      environment:
        DB_HOST: db
        DB_USER: nlquery
        DB_PASSWORD: postgres
        DB_NAME: nlquery-db
        DB_PORT: 5432
      volumes:
        - ./server:/app/server  # Mount your server directory

volumes:
  postgres_data:
