// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
	name, email, provider, createdAt, lastModified
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, provider, createdat, lastmodified
`

type CreateUserParams struct {
	Name         string
	Email        string
	Provider     pgtype.Text
	Createdat    pgtype.Timestamp
	Lastmodified pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Provider,
		arg.Createdat,
		arg.Lastmodified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.Createdat,
		&i.Lastmodified,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, provider, createdat, lastmodified FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.Createdat,
		&i.Lastmodified,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, provider, createdat, lastmodified FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Provider,
			&i.Createdat,
			&i.Lastmodified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :exec
UPDATE users
	SET provider = $2
	WHERE id = $1
`

type UpdateProviderParams struct {
	ID       int64
	Provider pgtype.Text
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) error {
	_, err := q.db.Exec(ctx, updateProvider, arg.ID, arg.Provider)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
	set name=$2,
	email=$3,
	lastModified=$4
WHERE id = $1
`

type UpdateUserParams struct {
	ID           int64
	Name         string
	Email        string
	Lastmodified pgtype.Timestamp
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Lastmodified,
	)
	return err
}
