// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             int64
	Name           string
	Email          string
	Provideruserid pgtype.Text
	Imagesrc       pgtype.Text
	Createdat      pgtype.Timestamp
	Lastmodified   pgtype.Timestamp
}
