/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1YY6czv7zFS
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import UploadButton from "../upload-file-button";

export function SearchBar() {
  return (
    <div className="flex items-center max-w-md w-full bg-background rounded-md border border-input shadow-sm">
      <div className="pl-3 pr-2">
        <SearchIcon className="w-5 h-5 text-muted-foreground" />
      </div>
      <Input
        type="search"
        placeholder="Search..."
        className="flex-1 py-2 pr-2 text-sm bg-transparent border-none focus:outline-none"
      />
      {/* <Button
        type="button"
        variant="ghost"
        className="rounded-md px-3 py-2 text-sm font-medium text-primary-background hover:bg-secondary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
      >
        <PaperclipIcon className="w-5 h-5" />
        <span className="sr-only">Attachments</span>
      </Button> */}
      <UploadButton />
      <Button
        type="submit"
        variant="ghost"
        className="rounded-md px-3 py-2 text-sm font-medium text-primary-background hover:bg-secondary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
      >
        <ArrowRightIcon className="w-5 h-5" />
      </Button>
    </div>
  );
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  );
}

function PaperclipIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
